apiVersion: v1
kind: Service
metadata:
  name: app-test
spec:
  type: ClusterIP
  selector:
    app: app-test
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: default
spec:
  parentRefs:
  - name: home-gateway
    namespace: nginx-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: app-test
      port: 80