apiVersion: v1
kind: Pod
metadata:
  name: "my-pod-with-init-containers"
  namespace: default
  labels:
    app: "my-pod-with-init-containers"
spec:
  containers:
  - name: my-pod-with-init-containers
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always
  initContainers:
  - name: init-myservice
    image: alpine/curl:latest
    command: ['sh', '-c', 'echo Initializing...; sleep 5; echo Initialization complete.']
  - name: init-config
    image: alpine/curl:latest
    command: ['sh', '-c', 'echo Setting up configuration...; sleep 3; echo Configuration setup complete.']
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi