apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-rolebinding
  namespace: default
subjects:
- kind: User
  name: markitos
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader-cluster-role
  apiGroup: rbac.authorization.k8s.io