apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-cluster-role
  namespace: development
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
